######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 20 00:29:17 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += detect.h
SOURCES += main.cpp
